- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that:
      # generic
      - mailserver_fqdn is not search("CHANGEME")
      - mailserver_autoconfig_fqdn is not search("CHANGEME")
      - mail_db_host is string
      - mail_db_name is string
      - mail_db_password is not search("CHANGEME")
      - mail_db_user is string
      - mailserver_https_mode in ["selfsigned", "letsencrypt_service", "letsencrypt_mod_md"]
      # dovecot
      - dovecot_fqdn is not search("CHANGEME")
      - dovecot_ldap_uri is not search("CHANGEME") or dovecot_auth_provider != "ldap"
      - dovecot_ldap_bind_dn is not search("CHANGEME") or dovecot_auth_provider != "ldap"
      - dovecot_ldap_bind_password is not search("CHANGEME") or dovecot_auth_provider != "ldap"
      - dovecot_ldap_base is not search("CHANGEME") or dovecot_auth_provider != "ldap"
      - dovecot_ldap_user_filter is string or dovecot_auth_provider != "ldap"
      - dovecot_auth_debug == dovecot_auth_debug | bool
      - dovecot_ldap_pass_attrs is string or dovecot_auth_provider != "ldap"
      - dovecot_firewalld_zones|type_debug == "list"
      - dovecot_listen_imap == dovecot_listen_imap | bool
      - dovecot_ssl_required == dovecot_ssl_required | bool
      - dovecot_auth_provider in ['pgsql', 'ldap']
      - dovecot_disable_plaintext_auth == dovecot_disable_plaintext_auth | bool
      - dovecot_enable_service == dovecot_enable_service | bool
      # postfix
      - postfix_fqdn is not search("CHANGEME")
      - postfix_ldap_uri is not search("CHANGEME") or postfix_auth_provider != "ldap"
      - postfix_ldap_bind_dn is not search("CHANGEME") or postfix_auth_provider != "ldap"
      - postfix_ldap_bind_password is not search("CHANGEME") or postfix_auth_provider != "ldap"
      - postfix_ldap_base is not search("CHANGEME") or postfix_auth_provider != "ldap"
      - postfix_mail_header_privacy == postfix_mail_header_privacy | bool
      - postfix_firewalld_zones|type_debug == "list"
      - postfix_auth_provider in ['pgsql', 'ldap']
      - postfix_enable_service == postfix_enable_service | bool
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/mail_dovecot"
