- name: install dovecot
  apt:
    state: present
    package:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-managesieved
      - dovecot-pgsql
      - dovecot-antispam
      - dovecot-fts-xapian
      - dovecot-ldap

- name: create dovecot directories
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: dovecot
    mode: "0770"
  with_items:
    - { dir: "/var/mail/vhosts" }
    - { dir: "/var/lib/dovecot/sieve/before.d", owner: "mail" }

- name: copy dovecot configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - { src: etc_dovecot_conf.d_10-mail.conf.j2, dest: /etc/dovecot/conf.d/10-mail.conf }
    - { src: etc_dovecot_conf.d_10-master.conf.j2, dest: /etc/dovecot/conf.d/10-master.conf }
    - { src: etc_dovecot_conf.d_10-auth.conf.j2, dest: /etc/dovecot/conf.d/10-auth.conf }
    - { src: etc_dovecot_conf.d_10-logging.conf.j2, dest: /etc/dovecot/conf.d/10-logging.conf }
    - { src: etc_dovecot_conf.d_10-ssl.conf.j2, dest: /etc/dovecot/conf.d/10-ssl.conf }
    - { src: etc_dovecot_conf.d_15-lda.conf.j2, dest: /etc/dovecot/conf.d/15-lda.conf }
    - { src: etc_dovecot_conf.d_20-imap.conf.j2, dest: /etc/dovecot/conf.d/20-imap.conf }
    - { src: etc_dovecot_conf.d_90-antispam.conf.j2, dest: /etc/dovecot/conf.d/90-antispam.conf }
    - { src: etc_dovecot_conf.d_90-plugin.conf.j2, dest: /etc/dovecot/conf.d/90-plugin.conf }
    - { src: etc_dovecot_conf.d_90-sieve.conf.j2, dest: /etc/dovecot/conf.d/90-sieve.conf }
    - { src: etc_dovecot_conf.d_auth-sql.conf.ext.j2, dest: /etc/dovecot/conf.d/auth-sql.conf.ext }
    - { src: etc_dovecot_dovecot-sql.conf.ext.j2, dest: /etc/dovecot/dovecot-sql.conf.ext }
    - { src: etc_dovecot_dovecot-ldap.conf.ext.j2, dest: /etc/dovecot/dovecot-ldap.conf.ext, mode: "0600" }
    - { src: var_lib_dovecot_sieve_before.d_no-spam.sieve.j2, dest: /var/lib/dovecot/sieve/before.d/no-spam.sieve, owner: "mail", group: "dovecot" }
    - { src: var_lib_dovecot_sieve_before.d_local.sieve.j2, dest: /var/lib/dovecot/sieve/before.d/local.sieve, owner: "mail", group: "dovecot" }
  notify: restart dovecot
  ignore_errors: "{{ ansible_check_mode }}"

# test IMAP/IMAPS ports locally:
# $ nc -Cv 127.0.0.1 143 or
# $ nc -Cv 127.0.0.1 993
# * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot (Debian) ready.
# A1 login user@CHANGEME.org CHANGEME_PASSWORD

##### SERVICE #####

- name: start/stop/enable/disable dovecot service
  service:
    name: dovecot
    state: "{{ 'started' if dovecot_enable_service else 'stopped' }}"
    enabled: "{{ 'yes' if dovecot_enable_service else 'no' }}"
  tags: services
  ignore_errors: "{{ ansible_check_mode }}"
