- name: create ansible facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"

- name: create postfix fact file
  template:
    src: etc_ansible_facts.d_postfix.fact.j2
    dest: /etc/ansible/facts.d/postfix.fact
    mode: "0644"
  notify: update ansible facts
  tags: postfix
  ignore_errors: "{{ ansible_check_mode }}"

- name: create opendkim fact file
  template:
    src: etc_ansible_facts.d_opendkim.fact.j2
    dest: /etc/ansible/facts.d/opendkim.fact
    mode: "0644"
  notify: update ansible facts
  tags: dovecot
  ignore_errors: "{{ ansible_check_mode }}"

- name: create dovecot fact file
  template:
    src: etc_ansible_facts.d_dovecot.fact.j2
    dest: /etc/ansible/facts.d/dovecot.fact
    mode: "0644"
  notify: update ansible facts
  tags: opendkim
  ignore_errors: "{{ ansible_check_mode }}"
