- name: copy dovecot & postfix fail2ban jail config
  copy:
    src: "etc_fail2ban_jail.d_{{ item }}.conf"
    dest: "/etc/fail2ban/jail.d/{{ item }}.conf"
    owner: root
    group: root
    mode: "0644"
  tags: fail2ban
  with_items:
    - dovecot
    - postfix
  notify: reload fail2ban
