- name: import variable checks tasks
  import_tasks: checks.yml
  tags:
    - dovecot
    - postfix
    - opendkim
    - mail
    - checks

- name: import self-signed certificates configuration tasks
  import_tasks: ssl-selfsigned.yml
  become: yes
  tags:
    - dovecot
    - postfix
    - opendkim
    - mail
    - ssl
  when:
    - mailserver_https_mode == 'selfsigned'

- name: import Let'sEncrypt configuration tasks
  import_tasks: letsencrypt.yml
  become: yes
  tags:
    - dovecot
    - postfix
    - opendkim
    - mail
    - ssl
  when:
    - mailserver_https_mode == 'letsencrypt'

- name: import SSL configuration tasks
  import_tasks: ssl.yml
  become: yes
  tags:
    - dovecot
    - postfix
    - opendkim
    - mail
    - ssl

- name: import postgresql configuration tasks
  import_tasks: postgresql.yml
  become: yes
  tags:
    - dovecot
    - postfix
    - mail
  when: dovecot_auth_provider == 'pgsql' or postfix_auth_provider == 'pgsql'

- name: import postfix configuration tasks
  import_tasks: postfix.yml
  become: yes
  tags:
    - postfix
    - mail

- name: import opendkim configuration tasks
  import_tasks: opendkim.yml
  become: yes
  tags:
    - opendkim
    - mail

- name: import users configuration tasks
  import_tasks: users.yml
  become: yes
  tags:
    - dovecot
    - mail

- name: import dovecot configuration tasks
  import_tasks: dovecot.yml
  become: yes
  tags:
    - dovecot
    - mail

- name: import maildirs configuration tasks
  import_tasks: maildirs.yml
  become: yes
  tags:
    - dovecot
    - mail

- name: import fail2ban configuration tasks
  import_tasks: fail2ban.yml
  become: yes
  tags:
    - dovecot
    - mail
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- name: import firewalld configuration tasks
  import_tasks: firewalld.yml
  become: yes
  tags:
    - dovecot
    - postfix
    - mail
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: import rsnapshot/backup configuration tasks
  import_tasks: backups.yml
  become: yes
  tags:
    - dovecot
    - postfix
    - mail
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed | bool

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags:
    - dovecot
    - postfix
    - opendkim

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - dovecot
    - postfix
    - opendkim
