- name: install opendkim and related packages
  apt:
    state: present
    package:
      - opendkim
      - opendkim-tools
  tags:
    - dependencies

- name: create postfix socket directory
  file:
    path: "/var/spool/postfix/opendkim"
    state: directory
    owner: "opendkim"
    group: "postfix"
    mode: "0770"
  ignore_errors: "{{ ansible_check_mode }}"

- name: copy opendkim configuration
  template:
    src: "etc_opendkim.conf.j2"
    dest: "/etc/opendkim.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart opendkim
  ignore_errors: "{{ ansible_check_mode }}"

- name: generate default opendkim private key
  command: >-
    opendkim-genkey \
        --directory=/etc/dkimkeys \
        --domain={{ mailserver_fqdn }} \
        --selector=default \
        --nosubdomains
  become_user: opendkim
  notify: restart opendkim
  ignore_errors: "{{ ansible_check_mode }}"

##### SERVICE #####

- name: start/stop/enable/disable opendkim service
  service:
    name: opendkim
    state: "{{ 'started' if opendkim_enable_service else 'stopped' }}"
    enabled: "{{ 'yes' if opendkim_enable_service else 'no' }}"
  tags: services
  ignore_errors: "{{ ansible_check_mode }}"
