- name: install requirements for SSL/TLS certificates generation
  apt:
    state: present
    package:
      - python3-openssl
      - ssl-cert

- name: generate openssl private key
  openssl_privatekey:
    path: "/etc/ssl/private/mailserver.key"
    owner: root
    group: root
    mode: "0600"
  notify:
    - restart dovecot
    - restart postfix
  ignore_errors: "{{ ansible_check_mode }}"

- name: generate openssl certificate signing request
  openssl_csr:
    path: "/etc/ssl/private/{{ mailserver }}.csr"
    privatekey_path: "/etc/ssl/private/{{mailserver_fqdn }}.key"
    common_name: "{{ mailserver_fqdn }}"
    key_usage: "digitalSignature,keyEncipherment"
    subject_alt_name: 'DNS:{{ dovecot_fqdn }},DNS:{{ postfix_fqdn }},DNS:{{ mailserver_autoconfig_fqdn }}'
    owner: root
    group: root
    mode: "0600"
  ignore_errors: "{{ ansible_check_mode }}"

- name: generate self-signed openssl certificate
  community.crypto.x509_certificate:
    path: "/etc/ssl/certs/{{ mailserver }}.crt"
    privatekey_path: "/etc/ssl/private/{{ mailserver }}.key"
    csr_path: "/etc/ssl/private/{{ mailserver }}.csr"
    provider: selfsigned
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart dovecot
    - restart postfix
  ignore_errors: "{{ ansible_check_mode }}"

- name: create local certificates directory on the controller
  become: no
  delegate_to: localhost
  file:
    path: "{{ playbook_dir }}/data/certificates/"
    state: directory
    mode: "0755"

- name: download self-signed certificate to the controller
  fetch:
    src: /etc/ssl/certs/dovecot.crt
    dest: "{{ playbook_dir }}/data/certificates/{{ dovecot_fqdn }}-dovecot.crt"
    flat: yes
