- name: Create vmail group
  group:
    name: "vmail"
    state: "present"
    gid: 5000
  tags: dovecot

- name: Create vmail user
  user:
    name: vmail
    group: vmail
    state: present
    uid: 5000
    home: "/var/mail/vhosts/"
    shell: "/usr/sbin/nologin"
  tags: dovecot
