- name: add eturnal APT repository
  copy:
    src: etc_apt_sources.list.d_eturnal.list
    dest: /etc/apt/sources.list.d/eturnal.list
    owner: root
    group: root
    mode: "0644"
  notify: update apt cache

- name: add eturnal APT signing keys
  copy:
    src: usr_share_keyrings_eturnal.gpg
    dest: /usr/share/keyrings/eturnal.gpg
    owner: root
    group: root
    mode: "0644"
  notify: update apt cache

# update APT cache for eturnal packages to become available
- name: run all notified handlers now
  meta: flush_handlers

- name: install eturnal package
  apt:
    state: present
    package:
      - eturnal

- name: copy eturnal configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: "{{ ansible_check_mode }}"
  notify: restart synapse
  with_items:
    - src: etc_eturnal.yml.j2
      dest: /etc/eturnal.yml
    - src: etc_matrix-synapse_conf.d_eturnal.yaml.j2
      dest: /etc/matrix-synapse/conf.d/eturnal.yaml

- name: apply configuration (flush handlers)
  meta: flush_handlers

##### SERVICE #####

- name: start/stop/enable/disable eturnal service
  service:
    name: eturnal
    state: "{{ 'started' if matrix_eturnal_enable_service else 'stopped' }}"
    enabled: "{{ 'yes' if matrix_eturnal_enable_service else 'no' }}"
  tags: services
  ignore_errors: "{{ ansible_check_mode }}"
