- name: import variable checks tasks
  import_tasks: checks.yml
  tags:
    - monitoring
    - rsyslog
    - checks

- name: import rsyslog server/CA certificates configuration tasks
  import_tasks: rsyslog-ssl-server.yml
  become: yes
  tags:
    - monitoring
    - rsyslog
    - ssl
  when: rsyslog_enable_receive | bool

- name: import rsyslog client certificates configuration tasks
  import_tasks: rsyslog-ssl-client.yml
  become: yes
  tags:
    - monitoring
    - rsyslog
    - ssl
  when: rsyslog_enable_forwarding | bool

- name: import rsyslog configuration tasks
  import_tasks: rsyslog.yml
  become: yes
  tags:
    - monitoring
    - rsyslog

- name: import logrotate configuration tasks
  import_tasks: logrotate.yml
  become: yes
  tags:
    - monitoring
    - logrotate

  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags:
    - monitoring
    - logrotate
    - rsyslog

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - monitoring
    - rsyslog
