- name: update apt cache
  apt:
    update_cache: yes
  become: yes
  tags:
    - dependencies

- name: upgrade all safe packages
  apt:
    upgrade: safe
  become: yes
  tags:
    - dependencies

- name: install necessities and nice-to-haves
  apt:
    pkg:
      - acl
      - build-essential
      - cron
      - debian-goodies
      - htop
      - iftop
      - iotop
      - molly-guard
      - mosh
      - screen
      - sudo
      - unattended-upgrades
      - vim
      - zsh
    state: present
  become: yes
  tags:
    - dependencies

- name: ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: "en_US.UTF-8"
    state: present
  become: yes

- name: install bash color prompt template
  copy:
    src: "bashrc-color-prompt"
    dest: "/etc/skel/.bashrc-color-prompt"
    owner: root
    group: root
    mode: "0655"
  become: yes
