- name: reload systemd unit files (searxng)
  become: yes
  become_user: searxng
  systemd:
    daemon_reload: yes
    scope: user

- name: restart searxng service
  become: yes
  become_user: searxng
  retries: 3
  systemd:
    name: container-searxng.service
    scope: user
    state: restarted
  when: searxng_enable_service | bool
